#CONTAINER_REGISTRY_SERVER: docker.io/davidxw
CONTAINER_REGISTRY_SERVER: azurestackhciacr.azurecr.io
LOOPING_VIDEO: mslow.mp4
MODEL_ENDPOINT: http://face-detect/image
RTMP_IN_URL: rtsp://rtsp-source:8554/sm1
RTMP_OUT_URL: rtsp://rtsp-out:8554/inf1
MODEL_FREQUENCY: 0.5
MODEL_THRESHOLD: 0.5
